// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGiJHbesrGJqJlTyOnpPJ8xvFP904qBpY',
    appId: '1:136214551449:web:57d09347c9d4f66e2a1108',
    messagingSenderId: '136214551449',
    projectId: 'filelocator-335b9',
    authDomain: 'filelocator-335b9.firebaseapp.com',
    storageBucket: 'filelocator-335b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkn5Qa_s0YgWBOoI3IxKzQUDWZR9txFq0',
    appId: '1:136214551449:android:de34cc6cb7d7e1412a1108',
    messagingSenderId: '136214551449',
    projectId: 'filelocator-335b9',
    storageBucket: 'filelocator-335b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARY9QqlBiXbCAUfK2ZhgpKqgH5yRMW5_E',
    appId: '1:136214551449:ios:99c930619d3017302a1108',
    messagingSenderId: '136214551449',
    projectId: 'filelocator-335b9',
    storageBucket: 'filelocator-335b9.appspot.com',
    iosBundleId: 'com.example.fileLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARY9QqlBiXbCAUfK2ZhgpKqgH5yRMW5_E',
    appId: '1:136214551449:ios:99c930619d3017302a1108',
    messagingSenderId: '136214551449',
    projectId: 'filelocator-335b9',
    storageBucket: 'filelocator-335b9.appspot.com',
    iosBundleId: 'com.example.fileLocator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGiJHbesrGJqJlTyOnpPJ8xvFP904qBpY',
    appId: '1:136214551449:web:5cd38eca46c36ff42a1108',
    messagingSenderId: '136214551449',
    projectId: 'filelocator-335b9',
    authDomain: 'filelocator-335b9.firebaseapp.com',
    storageBucket: 'filelocator-335b9.appspot.com',
  );

}